export const pimlocators = {
    addButton: "Add",
    firstName: "First Name",
    lastName: "Last Name",
    image: 'input[type="file"]',
    checkbox: '.oxd-switch-input',
    usernamecontainer: '.oxd-input oxd-input--active',
    userrname: 'input',
    status: ".oxd-radio-input",
    passwordcontainer: '.oxd-form-row.user-password-row',
    password: 'input[type="password"]',
    //confirmpasswordcontainer: '.oxd-input oxd-input--active',
    confirmpassword: '.oxd-input-group:has-text("Confirm Password") input[type="password"]',
    savebutton: "Save",
}